### ISSUE TITLE
Training & Knowledge sharing checklist for the new event

### ISSUE THREAD

**Issue by iamtekson** [osgeonepal/rollingdoc#18]
The idea behind this issue is to add a standard checklist to follow before organizing any event. It is like a proposal with a number of volunteers to follow to create a good event.

For now, I have following things in mind:

- [ ] When?
- [ ] Number of volunteer required?
- [ ] Estimated budget
- [ ] Estimated length of the training
- [ ] Create a meeting link.
- [ ] Communication with speakers?
    - [ ] Topic of the presentation
    - [ ] Short intro about speaker
    - [ ] Affiliation
    - [ ] Photo
    - [ ] Ask whether the speaker is comfortable going live on YouTube or not
- [ ] Event posters should be shared at least a week before
- [ ] Add more .......

**Comment by iamtekson** [comment]
More info;

- [ ] Is the training related to open source geospatial community?
- [ ] Invitation to participate and speakers


Divide checklists into two catagories `pre-event` & `post-event`. You might also need to merge the previous checklist with below,

Post Event:

- [ ] Post on social media
- [ ] summary of the event
- [ ] Thank you note for the speakers & participants 

Pre-event:

- [ ] Communication/discussion started in discord channel (training & collaboration)
- [ ] Decide target group, make sure selection of the speaker is relevant to the event
- [ ] Checklist pass for speaker
    - [ ] Speaker is active in open source geospatial community 
    - [ ] Had relevant experience
    - [ ] Not associated with business marketing 
    - [ ] tbd....
- [ ] Ask for the volunteers 
    - [ ] Event facilitator 
    - [ ] Social media coordinator
    - [ ] Email & meeting link manager
    - [ ] Note taking 

- [ ] Ask for a poster (poster and communication channel)
- [ ] Event outline (what are the topics that will be covered, what to expect, timeline)

**Comment by iamtekson** [comment]
cc: @Lalitgis @Pratichhya

**Comment by kshitijrajsharma** [comment]
I am willing to host Jitsi in my personal instance, Let's do that ! Lets try to migrate from facebook / google as well !

**Comment by Lalitgis** [comment]
yes di, I did go through this list and added some check list that came
across my mind.


Mr. Lalit Bc

 Institute of Agriculture and Animal Science

M.Sc. Animal Science

+9779868365688

***@***.***
------------------------------
  <https://www.facebook.com/lalit.bc.90>
<https://instagram.com/lalit_iaas?igshid=bj9tvoetdn79>
<https://www.linkedin.com/in/lalit-bc-67832a140>
<https://www.youtube.com/channel/UC4pt3AUxKziC4qZ_Qr4aXqQ>

**Comment by Pratichhya** [comment]
Thank you, @Lalitgis; in that sense, let us give it a first try with next week's geo-series event. @iamtekson @kshitijrajsharma, please share your feedback and comments on this. Also, please correct me if there is another event prior to the talk series.

**Comment by kshitijrajsharma** [comment]
@Pratichhya  we have listed the checklist from top of our head before , I think we are good with revisions !

**Comment by iamtekson** [comment]
I am closing it for now, since we already implemented the issue template.
